global:
  scrape_interval: 5s # ColecteazÄƒ date la fiecare 5 secunde (pentru demo rapid)

scrape_configs:
  - job_name: 'fastapi_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']